// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

package com.panduit.graph;

public final class GraphProtos {
  private GraphProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EdgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:graph.Edge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 from = 1;</code>
     */
    int getFrom();

    /**
     * <code>optional int32 to = 2;</code>
     */
    int getTo();

    /**
     * <code>optional string label = 3;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 3;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>optional double weight = 4;</code>
     */
    double getWeight();
  }
  /**
   * Protobuf type {@code graph.Edge}
   */
  public  static final class Edge extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:graph.Edge)
      EdgeOrBuilder {
    // Use Edge.newBuilder() to construct.
    private Edge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Edge() {
      from_ = 0;
      to_ = 0;
      label_ = "";
      weight_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Edge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              from_ = input.readInt32();
              break;
            }
            case 16: {

              to_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 33: {

              weight_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panduit.graph.GraphProtos.internal_static_graph_Edge_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panduit.graph.GraphProtos.internal_static_graph_Edge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panduit.graph.GraphProtos.Edge.class, com.panduit.graph.GraphProtos.Edge.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>optional int32 from = 1;</code>
     */
    public int getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>optional int32 to = 2;</code>
     */
    public int getTo() {
      return to_;
    }

    public static final int LABEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 3;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>optional string label = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 4;
    private double weight_;
    /**
     * <code>optional double weight = 4;</code>
     */
    public double getWeight() {
      return weight_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0) {
        output.writeInt32(1, from_);
      }
      if (to_ != 0) {
        output.writeInt32(2, to_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, label_);
      }
      if (weight_ != 0D) {
        output.writeDouble(4, weight_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, from_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, to_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, label_);
      }
      if (weight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, weight_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panduit.graph.GraphProtos.Edge)) {
        return super.equals(obj);
      }
      com.panduit.graph.GraphProtos.Edge other = (com.panduit.graph.GraphProtos.Edge) obj;

      boolean result = true;
      result = result && (getFrom()
          == other.getFrom());
      result = result && (getTo()
          == other.getTo());
      result = result && getLabel()
          .equals(other.getLabel());
      result = result && (
          java.lang.Double.doubleToLongBits(getWeight())
          == java.lang.Double.doubleToLongBits(
              other.getWeight()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWeight()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Edge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Edge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Edge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panduit.graph.GraphProtos.Edge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code graph.Edge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:graph.Edge)
        com.panduit.graph.GraphProtos.EdgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Edge_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panduit.graph.GraphProtos.Edge.class, com.panduit.graph.GraphProtos.Edge.Builder.class);
      }

      // Construct using com.panduit.graph.GraphProtos.Edge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = 0;

        to_ = 0;

        label_ = "";

        weight_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Edge_descriptor;
      }

      public com.panduit.graph.GraphProtos.Edge getDefaultInstanceForType() {
        return com.panduit.graph.GraphProtos.Edge.getDefaultInstance();
      }

      public com.panduit.graph.GraphProtos.Edge build() {
        com.panduit.graph.GraphProtos.Edge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.panduit.graph.GraphProtos.Edge buildPartial() {
        com.panduit.graph.GraphProtos.Edge result = new com.panduit.graph.GraphProtos.Edge(this);
        result.from_ = from_;
        result.to_ = to_;
        result.label_ = label_;
        result.weight_ = weight_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panduit.graph.GraphProtos.Edge) {
          return mergeFrom((com.panduit.graph.GraphProtos.Edge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panduit.graph.GraphProtos.Edge other) {
        if (other == com.panduit.graph.GraphProtos.Edge.getDefaultInstance()) return this;
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (other.getWeight() != 0D) {
          setWeight(other.getWeight());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panduit.graph.GraphProtos.Edge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panduit.graph.GraphProtos.Edge) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int from_ ;
      /**
       * <code>optional int32 from = 1;</code>
       */
      public int getFrom() {
        return from_;
      }
      /**
       * <code>optional int32 from = 1;</code>
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <code>optional int32 to = 2;</code>
       */
      public int getTo() {
        return to_;
      }
      /**
       * <code>optional int32 to = 2;</code>
       */
      public Builder setTo(int value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 3;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private double weight_ ;
      /**
       * <code>optional double weight = 4;</code>
       */
      public double getWeight() {
        return weight_;
      }
      /**
       * <code>optional double weight = 4;</code>
       */
      public Builder setWeight(double value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double weight = 4;</code>
       */
      public Builder clearWeight() {
        
        weight_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:graph.Edge)
    }

    // @@protoc_insertion_point(class_scope:graph.Edge)
    private static final com.panduit.graph.GraphProtos.Edge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panduit.graph.GraphProtos.Edge();
    }

    public static com.panduit.graph.GraphProtos.Edge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Edge>
        PARSER = new com.google.protobuf.AbstractParser<Edge>() {
      public Edge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Edge(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Edge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Edge> getParserForType() {
      return PARSER;
    }

    public com.panduit.graph.GraphProtos.Edge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GraphOrBuilder extends
      // @@protoc_insertion_point(interface_extends:graph.Graph)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    java.util.List<com.panduit.graph.GraphProtos.Edge> 
        getEdgeList();
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    com.panduit.graph.GraphProtos.Edge getEdge(int index);
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    int getEdgeCount();
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    java.util.List<? extends com.panduit.graph.GraphProtos.EdgeOrBuilder> 
        getEdgeOrBuilderList();
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    com.panduit.graph.GraphProtos.EdgeOrBuilder getEdgeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code graph.Graph}
   */
  public  static final class Graph extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:graph.Graph)
      GraphOrBuilder {
    // Use Graph.newBuilder() to construct.
    private Graph(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Graph() {
      edge_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Graph(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                edge_ = new java.util.ArrayList<com.panduit.graph.GraphProtos.Edge>();
                mutable_bitField0_ |= 0x00000001;
              }
              edge_.add(
                  input.readMessage(com.panduit.graph.GraphProtos.Edge.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          edge_ = java.util.Collections.unmodifiableList(edge_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.panduit.graph.GraphProtos.internal_static_graph_Graph_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.panduit.graph.GraphProtos.internal_static_graph_Graph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.panduit.graph.GraphProtos.Graph.class, com.panduit.graph.GraphProtos.Graph.Builder.class);
    }

    public static final int EDGE_FIELD_NUMBER = 1;
    private java.util.List<com.panduit.graph.GraphProtos.Edge> edge_;
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    public java.util.List<com.panduit.graph.GraphProtos.Edge> getEdgeList() {
      return edge_;
    }
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    public java.util.List<? extends com.panduit.graph.GraphProtos.EdgeOrBuilder> 
        getEdgeOrBuilderList() {
      return edge_;
    }
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    public int getEdgeCount() {
      return edge_.size();
    }
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    public com.panduit.graph.GraphProtos.Edge getEdge(int index) {
      return edge_.get(index);
    }
    /**
     * <code>repeated .graph.Edge edge = 1;</code>
     */
    public com.panduit.graph.GraphProtos.EdgeOrBuilder getEdgeOrBuilder(
        int index) {
      return edge_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < edge_.size(); i++) {
        output.writeMessage(1, edge_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < edge_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, edge_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.panduit.graph.GraphProtos.Graph)) {
        return super.equals(obj);
      }
      com.panduit.graph.GraphProtos.Graph other = (com.panduit.graph.GraphProtos.Graph) obj;

      boolean result = true;
      result = result && getEdgeList()
          .equals(other.getEdgeList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getEdgeCount() > 0) {
        hash = (37 * hash) + EDGE_FIELD_NUMBER;
        hash = (53 * hash) + getEdgeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Graph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Graph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.panduit.graph.GraphProtos.Graph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.panduit.graph.GraphProtos.Graph prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code graph.Graph}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:graph.Graph)
        com.panduit.graph.GraphProtos.GraphOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Graph_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Graph_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.panduit.graph.GraphProtos.Graph.class, com.panduit.graph.GraphProtos.Graph.Builder.class);
      }

      // Construct using com.panduit.graph.GraphProtos.Graph.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEdgeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.panduit.graph.GraphProtos.internal_static_graph_Graph_descriptor;
      }

      public com.panduit.graph.GraphProtos.Graph getDefaultInstanceForType() {
        return com.panduit.graph.GraphProtos.Graph.getDefaultInstance();
      }

      public com.panduit.graph.GraphProtos.Graph build() {
        com.panduit.graph.GraphProtos.Graph result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.panduit.graph.GraphProtos.Graph buildPartial() {
        com.panduit.graph.GraphProtos.Graph result = new com.panduit.graph.GraphProtos.Graph(this);
        int from_bitField0_ = bitField0_;
        if (edgeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            edge_ = java.util.Collections.unmodifiableList(edge_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.edge_ = edge_;
        } else {
          result.edge_ = edgeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.panduit.graph.GraphProtos.Graph) {
          return mergeFrom((com.panduit.graph.GraphProtos.Graph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.panduit.graph.GraphProtos.Graph other) {
        if (other == com.panduit.graph.GraphProtos.Graph.getDefaultInstance()) return this;
        if (edgeBuilder_ == null) {
          if (!other.edge_.isEmpty()) {
            if (edge_.isEmpty()) {
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEdgeIsMutable();
              edge_.addAll(other.edge_);
            }
            onChanged();
          }
        } else {
          if (!other.edge_.isEmpty()) {
            if (edgeBuilder_.isEmpty()) {
              edgeBuilder_.dispose();
              edgeBuilder_ = null;
              edge_ = other.edge_;
              bitField0_ = (bitField0_ & ~0x00000001);
              edgeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEdgeFieldBuilder() : null;
            } else {
              edgeBuilder_.addAllMessages(other.edge_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.panduit.graph.GraphProtos.Graph parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.panduit.graph.GraphProtos.Graph) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.panduit.graph.GraphProtos.Edge> edge_ =
        java.util.Collections.emptyList();
      private void ensureEdgeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          edge_ = new java.util.ArrayList<com.panduit.graph.GraphProtos.Edge>(edge_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panduit.graph.GraphProtos.Edge, com.panduit.graph.GraphProtos.Edge.Builder, com.panduit.graph.GraphProtos.EdgeOrBuilder> edgeBuilder_;

      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public java.util.List<com.panduit.graph.GraphProtos.Edge> getEdgeList() {
        if (edgeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edge_);
        } else {
          return edgeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public int getEdgeCount() {
        if (edgeBuilder_ == null) {
          return edge_.size();
        } else {
          return edgeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public com.panduit.graph.GraphProtos.Edge getEdge(int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);
        } else {
          return edgeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder setEdge(
          int index, com.panduit.graph.GraphProtos.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.set(index, value);
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder setEdge(
          int index, com.panduit.graph.GraphProtos.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder addEdge(com.panduit.graph.GraphProtos.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder addEdge(
          int index, com.panduit.graph.GraphProtos.Edge value) {
        if (edgeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgeIsMutable();
          edge_.add(index, value);
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder addEdge(
          com.panduit.graph.GraphProtos.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder addEdge(
          int index, com.panduit.graph.GraphProtos.Edge.Builder builderForValue) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder addAllEdge(
          java.lang.Iterable<? extends com.panduit.graph.GraphProtos.Edge> values) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, edge_);
          onChanged();
        } else {
          edgeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder clearEdge() {
        if (edgeBuilder_ == null) {
          edge_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          edgeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public Builder removeEdge(int index) {
        if (edgeBuilder_ == null) {
          ensureEdgeIsMutable();
          edge_.remove(index);
          onChanged();
        } else {
          edgeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public com.panduit.graph.GraphProtos.Edge.Builder getEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public com.panduit.graph.GraphProtos.EdgeOrBuilder getEdgeOrBuilder(
          int index) {
        if (edgeBuilder_ == null) {
          return edge_.get(index);  } else {
          return edgeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public java.util.List<? extends com.panduit.graph.GraphProtos.EdgeOrBuilder> 
           getEdgeOrBuilderList() {
        if (edgeBuilder_ != null) {
          return edgeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edge_);
        }
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public com.panduit.graph.GraphProtos.Edge.Builder addEdgeBuilder() {
        return getEdgeFieldBuilder().addBuilder(
            com.panduit.graph.GraphProtos.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public com.panduit.graph.GraphProtos.Edge.Builder addEdgeBuilder(
          int index) {
        return getEdgeFieldBuilder().addBuilder(
            index, com.panduit.graph.GraphProtos.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .graph.Edge edge = 1;</code>
       */
      public java.util.List<com.panduit.graph.GraphProtos.Edge.Builder> 
           getEdgeBuilderList() {
        return getEdgeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.panduit.graph.GraphProtos.Edge, com.panduit.graph.GraphProtos.Edge.Builder, com.panduit.graph.GraphProtos.EdgeOrBuilder> 
          getEdgeFieldBuilder() {
        if (edgeBuilder_ == null) {
          edgeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.panduit.graph.GraphProtos.Edge, com.panduit.graph.GraphProtos.Edge.Builder, com.panduit.graph.GraphProtos.EdgeOrBuilder>(
                  edge_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          edge_ = null;
        }
        return edgeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:graph.Graph)
    }

    // @@protoc_insertion_point(class_scope:graph.Graph)
    private static final com.panduit.graph.GraphProtos.Graph DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.panduit.graph.GraphProtos.Graph();
    }

    public static com.panduit.graph.GraphProtos.Graph getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Graph>
        PARSER = new com.google.protobuf.AbstractParser<Graph>() {
      public Graph parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Graph(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Graph> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Graph> getParserForType() {
      return PARSER;
    }

    public com.panduit.graph.GraphProtos.Graph getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_graph_Edge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_graph_Edge_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_graph_Graph_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_graph_Graph_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013graph.proto\022\005graph\"?\n\004Edge\022\014\n\004from\030\001 \001" +
      "(\005\022\n\n\002to\030\002 \001(\005\022\r\n\005label\030\003 \001(\t\022\016\n\006weight\030" +
      "\004 \001(\001\"\"\n\005Graph\022\031\n\004edge\030\001 \003(\0132\013.graph.Edg" +
      "eB \n\021com.panduit.graphB\013GraphProtosb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_graph_Edge_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_graph_Edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_graph_Edge_descriptor,
        new java.lang.String[] { "From", "To", "Label", "Weight", });
    internal_static_graph_Graph_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_graph_Graph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_graph_Graph_descriptor,
        new java.lang.String[] { "Edge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
